all: target

target:
	g++ mygrep_dir/main.cpp  -o mygrep /usr/lib/x86_64-linux-gnu/libboost_program_options.so /usr/lib/x86_64-linux-gnu/libboost_system.so /usr/lib/x86_64-linux-gnu/libboost_filesystem.so -std=c++14

